"""add xp tracking

Revision ID: acf1fd91dcf8
Revises: 53e7d576b4d2
Create Date: 2026-10-08 19:56:15.523915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acf1fd91dcf8'
down_revision = '53e7d576b4d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_attempt', schema=None) as batch_op:
        batch_op.add_column(sa.Column('xp_earned', sa.Integer(), server_default='0', nullable=False))

    with op.batch_alter_table('quiz_attempt_answer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('xp_awarded', sa.Integer(), server_default='0', nullable=False))

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_xp', sa.Integer(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_column('total_xp')

    with op.batch_alter_table('quiz_attempt_answer', schema=None) as batch_op:
        batch_op.drop_column('xp_awarded')

    with op.batch_alter_table('quiz_attempt', schema=None) as batch_op:
        batch_op.drop_column('xp_earned')

    # ### end Alembic commands ###
